version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  DATABASE_HOST: db
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}

services:
  app:
    image: ghcr.io/naufalfachrian/waterlily:0.0.1
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - waterlily
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: ghcr.io/naufalfachrian/waterlily:0.0.1
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks:
      - waterlily
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: ghcr.io/naufalfachrian/waterlily:0.0.1
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks:
      - waterlily
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    networks:
      - waterlily

networks:
  waterlily:
